//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SecureCoreFinal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sectors
    {
        public int idSector { get; set; }
        public string CodeSector { get; set; }
        public string DescSector { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> idRegion { get; set; }
    }
}
